arviz 0.6.1 (Apache-2.0) has 1 incompatibilities in [tree_created]:
arviz 
  netcdf4 1.5.3 [arviz ()]
    numpy 1.18.0 [arviz (>=1.12)] [netcdf4 (>=1.7)] [xarray (>=1.14)] [pandas (>=1.13.3)] [scipy (>=1.13.3)] [cftime ()]
    cftime 1.0.4.2 (INCOMPATIBLE! HAS GPL-3.0-only) [netcdf4 ()]
  xarray 0.14.1 [arviz (>=0.11)]
    pandas 0.25.3 [arviz (>=0.23)] [xarray (>=0.24)]
      pytz 2019.1 [pandas (>=2017.2)]
      python-dateutil 2.8.1 [pandas (>=2.6.1)]
    numpy 1.18.0 [arviz (>=1.12)] [netcdf4 (>=1.7)] [xarray (>=1.14)] [pandas (>=1.13.3)] [scipy (>=1.13.3)] [cftime ()]
  pandas 0.25.3 [arviz (>=0.23)] [xarray (>=0.24)]
    numpy 1.18.0 [arviz (>=1.12)] [netcdf4 (>=1.7)] [xarray (>=1.14)] [pandas (>=1.13.3)] [scipy (>=1.13.3)] [cftime ()]
    pytz 2019.1 [pandas (>=2017.2)]
    python-dateutil 2.8.1 [pandas (>=2.6.1)]
      six 1.12.0 [packaging ()] [python-dateutil (>=1.5)]
  packaging 19.2 [arviz ()]
    six 1.12.0 [packaging ()] [python-dateutil (>=1.5)]
    pyparsing 2.4.6 [packaging (>=2.0.2)]
  scipy 1.4.1 [arviz (>=0.19)]
    numpy 1.18.0 [arviz (>=1.12)] [netcdf4 (>=1.7)] [xarray (>=1.14)] [pandas (>=1.13.3)] [scipy (>=1.13.3)] [cftime ()]
  numpy 1.18.0 [arviz (>=1.12)] [netcdf4 (>=1.7)] [xarray (>=1.14)] [pandas (>=1.13.3)] [scipy (>=1.13.3)] [cftime ()]
  matplotlib 3.1.2 [arviz (>=3.0)]
