metaflow 2.7.14 (Apache-2.0) has 1 incompatibilities in [tree_created]:
metaflow 
  pylint 2.15.5 (INCOMPATIBLE! HAS GPL-2.0-or-later) [metaflow ()]
    tomli 2.0.1 [pylint (>=1.1.0)]
    typing-extensions 4.4.0 [pylint (>=3.10.0)] [astroid (>=3.10)]
    tomlkit 0.11.6 [pylint (>=0.10.1)]
    mccabe 0.7.0 [pylint (<0.8,>=0.6)]
    isort 5.10.0 [pylint (<6,>=4.2.5)]
    astroid 2.12.12 [pylint (<=2.14.0-dev0,>=2.12.12)]
      wrapt 1.14.1 [astroid (<2,>=1.11)]
      lazy-object-proxy 1.8.0 [astroid (>=1.4.0)]
    platformdirs 2.5.2 [pylint (>=2.2.0)]
    dill 0.3.6 [pylint (>=0.2)]
  boto3 1.26.1 [metaflow ()]
    s3transfer 0.6.0 [boto3 (<0.7.0,>=0.6.0)]
      botocore 1.29.1 [boto3 (<1.30.0,>=1.29.1)] [s3transfer (<2.0a.0,>=1.12.36)]
        python-dateutil 2.8.2 [botocore (<3.0.0,>=2.1)]
          six 1.16.0 [python-dateutil (>=1.5)]
    jmespath 1.0.1 [boto3 (<2.0.0,>=0.7.1)] [botocore (<2.0.0,>=0.7.1)]
    botocore 1.29.1 [boto3 (<1.30.0,>=1.29.1)] [s3transfer (<2.0a.0,>=1.12.36)]
      urllib3 1.26.12 [requests (<1.27,>=1.21.1)] [botocore (<1.27,>=1.25.4)]
      python-dateutil 2.8.2 [botocore (<3.0.0,>=2.1)]
        six 1.16.0 [python-dateutil (>=1.5)]
  requests 2.28.1 [metaflow ()]
    certifi 2022.9.24 [requests (>=2017.4.17)]
    urllib3 1.26.12 [requests (<1.27,>=1.21.1)] [botocore (<1.27,>=1.25.4)]
    idna 3.3 [requests (<4,>=2.5)]
    charset-normalizer 2.1.0 [requests (<3,>=2)]
